# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfx" do
  name "tfx"
  desc "TFx is a standalone CLI tool for HCP Terraform and Terraform Enterprise."
  homepage "https://tfx.rocks/"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfx"

  on_macos do
    on_intel do
      url "https://github.com/straubt1/tfx/releases/download/v#{version}/tfx_Darwin_x86_64.tar.gz"
      sha256 "1cfcce7c50ce5357138eccfa11b6b044c5b16e0cce97b2b5ae46f3f453e7e86b"
      rename "tfx_Darwin_x86_64/tfx", "tfx"
    end
    on_arm do
      url "https://github.com/straubt1/tfx/releases/download/v#{version}/tfx_Darwin_arm64.tar.gz"
      sha256 "0719875ce7269a7ceb6e026bf1488e8b11ce12749b6e380c4670647be94577ac"
      rename "tfx_Darwin_arm64/tfx", "tfx"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/straubt1/tfx/releases/download/v#{version}/tfx_Linux_x86_64.tar.gz"
      sha256 "aad92c800ff93ef31a2e62e59fabbf28f01a55e4ea69fc6a172867c46a1b1d43"
      rename "tfx_Linux_x86_64/tfx", "tfx"
    end
    on_arm do
      url "https://github.com/straubt1/tfx/releases/download/v#{version}/tfx_Linux_arm64.tar.gz"
      sha256 "dd7c3cbc03880ad09f1e044bce76f9649b3f2a5ca6ef5a92119deac8b8b69979"
      rename "tfx_Linux_arm64/tfx", "tfx"
    end
  end

  # No zap stanza required
end
