# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfxLatest < Formula
  desc "TFx latest build from main branch (unstable)."
  homepage "https://tfx.rocks/"
  version "latest"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/straubt1/tfx/releases/download/latest/tfx-latest_Darwin_x86_64.tar.gz"
      sha256 "c7982d37052c59670a4954da265131e15b87ddf138294b379780944bc335409f"

      define_method(:install) do
        bin.install "tfx-latest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/straubt1/tfx/releases/download/latest/tfx-latest_Darwin_arm64.tar.gz"
      sha256 "b1040fec54fbe8a509c97f871b9405b5f4c21a31feda8a9e5f13bb1dfa82eae5"

      define_method(:install) do
        bin.install "tfx-latest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/straubt1/tfx/releases/download/latest/tfx-latest_Linux_x86_64.tar.gz"
      sha256 "2aa4c004f22a4676b9f7d1b79a93402599db65356f7dc5170de7bbfefac73aad"
      define_method(:install) do
        bin.install "tfx-latest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/straubt1/tfx/releases/download/latest/tfx-latest_Linux_arm64.tar.gz"
      sha256 "1f8f72d9d64a2fcb17525f058bce5ed0364715645b3d3e19c1f3359131eab8a0"
      define_method(:install) do
        bin.install "tfx-latest"
      end
    end
  end
end
