# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfxLatest < Formula
  desc "TFx latest build from main branch (unstable)."
  homepage "https://tfx.rocks/"
  version "latest"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/straubt1/tfx/releases/download/latest/tfx-latest_Darwin_x86_64.tar.gz"
      sha256 "f134b5c9ea63a352abbdeec742d9da57fcd180c808af59d1ca9098310d712d0e"

      define_method(:install) do
        bin.install "tfx-latest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/straubt1/tfx/releases/download/latest/tfx-latest_Darwin_arm64.tar.gz"
      sha256 "c3e1ab54afcf6c601e1e2fa5e92721ca1c264f4848a1baac644319d62e71017c"

      define_method(:install) do
        bin.install "tfx-latest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/straubt1/tfx/releases/download/latest/tfx-latest_Linux_x86_64.tar.gz"
      sha256 "ec8c6f83cb7501ea0b908f48d0d1a0d3b09470ef6893e7e939121807bf55d077"
      define_method(:install) do
        bin.install "tfx-latest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/straubt1/tfx/releases/download/latest/tfx-latest_Linux_arm64.tar.gz"
      sha256 "1f9fbe3f05341a65ca272301f683705edc59e5d9cf80fa18e8cd616e16cb408d"
      define_method(:install) do
        bin.install "tfx-latest"
      end
    end
  end
end
