# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfxLatest < Formula
  desc "TFx latest build from main branch (unstable)."
  homepage "https://tfx.rocks/"
  version "latest"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/straubt1/tfx/releases/download/latest/tfx-latest_Darwin_x86_64.tar.gz"
      sha256 "44e187d73ce6fad12d47537d0f418266b8b1af7566bd2782b4d662b60681115a"

      define_method(:install) do
        bin.install "tfx-latest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/straubt1/tfx/releases/download/latest/tfx-latest_Darwin_arm64.tar.gz"
      sha256 "3c13b5bdad4af68d81313f80c40466e28693c45396f0a98177425120a5821d79"

      define_method(:install) do
        bin.install "tfx-latest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/straubt1/tfx/releases/download/latest/tfx-latest_Linux_x86_64.tar.gz"
      sha256 "6926061a3f1d4f02bc60f20cd705b9574756fb9ee5e154cf39cf345f7be04093"
      define_method(:install) do
        bin.install "tfx-latest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/straubt1/tfx/releases/download/latest/tfx-latest_Linux_arm64.tar.gz"
      sha256 "abd0059ab70c17cfdb3d993c9079cee979f6608da97879f1ded4f1ba8a845080"
      define_method(:install) do
        bin.install "tfx-latest"
      end
    end
  end
end
